version: "3"

services:
  mynginx:
    build:
      context: nginx
    container_name: mynginx
    tty: true
    networks:
      - node-network
    depends_on:
      - myapp
    ports:
      - 8080:80

  myapp:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 40s docker-entrypoint.sh node index.js
    command: node index.js
    networks:
      - node-network
    volumes:
      - ./node:/usr/src/app
    tty: true
    # depends_on:
    #   - db

  db:
    user: mysql
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      # - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network
    ports:
      - 3306:3306

networks:
  node-network:
    driver: bridge
